name: 镜像同步请求
description: 请求同步 Docker 镜像到目标仓库
title: "[image-mirror]"
labels: ["pending-validation"]
body:
  - type: textarea
    id: images
    attributes:
      label: 镜像列表
      description: |
        请输入镜像列表，每行一个镜像，格式要求如下：
        - 每个镜像必须包含 `:tag` 标签
        - 支持格式：`image:tag`、`namespace/image:tag`、`registry/namespace/image:tag`  
        
        示例：
        ```
        nginx:1.21
        redis:6.2
        gcr.io/kubernetes/kube-proxy:v1.18.3
        ```

      placeholder: |
        nginx:1.21
        redis:6.2
        gcr.io/kubernetes/kube-proxy:v1.18.3
    validations:
      required: true
      pattern: '^([a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+|[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+|[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+)(\r?\n([a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+|[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+|[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+))*$'
